Traceback (most recent call last):
  File "/Users/parikshithkulkarni/PycharmProjects/pythonProject/learn/raise_assert.py", line 4, in <module>
    raise Exception('This is a sample exception')
Exception: This is a sample exception
